# Generated by Django 5.2.17 on 2026-09-07 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('full', 'Full'), ('cut_only', 'Cut only'), ('subtitles_only', 'Subtitles only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('ingest', 'Ingest'), ('transcribe', 'Transcribe'), ('analyze', 'Analyze'), ('align', 'Align'), ('cut', 'Cut'), ('edit', 'Edit'), ('subtitles', 'Subtitles'), ('translate', 'Translate'), ('render', 'Render')], max_length=20)),
                ('queue', models.CharField(choices=[('io', 'IO'), ('cpu', 'CPU'), ('gpu', 'GPU')], default='cpu', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('logs', models.JSONField(blank=True, default=list)),
                ('segment_index', models.IntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.pipelinerun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_builtin', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.processingprofile'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('ingested', 'Ingested'), ('transcribed', 'Transcribed'), ('analyzed', 'Analyzed'), ('ready', 'Ready'), ('error', 'Error')], default='empty', max_length=20)),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('hook', models.CharField(blank=True, default='', max_length=255)),
                ('start_text', models.CharField(blank=True, default='', max_length=512)),
                ('end_text', models.CharField(blank=True, default='', max_length=512)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('cut', 'Cut'), ('edited', 'Edited'), ('rendered', 'Rendered'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.pipelinerun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.project')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='pt', max_length=10)),
                ('source', models.CharField(default='whisper', max_length=20)),
                ('model', models.CharField(default='', max_length=120)),
                ('segments', models.JSONField(default=list)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('fingerprint', models.CharField(default='', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', 'Source'), ('downloaded', 'Downloaded'), ('normalized', 'Normalized'), ('cut', 'Cut'), ('edited', 'Edited'), ('subtitled', 'Subtitled'), ('final', 'Final'), ('preview', 'Preview'), ('thumbnail', 'Thumbnail')], max_length=20)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='video/mp4', max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, default='', max_length=60)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('segment_index', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.videoasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_artifacts', to='projects.project')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.videoasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
