# Generated by Django 5.2.17 on 2026-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactcache',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='artifactcache',
            constraint=models.UniqueConstraint(fields=('project', 'stage', 'fingerprint'), name='uniq_artifactcache_project_stage_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='transcription',
            constraint=models.UniqueConstraint(fields=('project', 'fingerprint'), name='uniq_transcription_project_fingerprint'),
        ),
    ]
